trigger:
  - main

pool:
  name: NayaInfra

steps:

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
    backendServiceArm: 'NayaInfra'
    backendAzureRmStorageAccountName: 'gssstrg'
    backendAzureRmContainerName: 'pipelinestrg'
    backendAzureRmKey: 'backend.tfstate'


